INSERT INTO public.site_content (content_key, category, label, sort_order, value_es, value_en, value_ru) VALUES
  ('about_section_label', 'about_page', 'About — section label (small caps above title)', 10,
    'El terapeuta', 'The therapist', 'Терапевт'),
  ('about_title', 'about_page', 'About — page title (H1)', 11,
    'Sobre mí', 'About me', 'Обо мне'),
  ('about_bio', 'about_page', 'About — biography (separate paragraphs with a blank line)', 12,
    E'Me llamo Elias y soy masajista profesional en Valencia. Llevo más de 8 años dedicándome a esto, y cada día me confirma que elegí bien.\n\nMe formé en fisioterapia y me especialicé en técnicas de masaje terapéutico, deportivo y relajante. He trabajado con deportistas, personas con dolor crónico y con quienes simplemente necesitan parar.\n\nMi enfoque es sencillo: escuchar al cuerpo, entender lo que necesita y trabajar con precisión. No hago protocolos genéricos. Cada sesión es diferente porque cada persona lo es.\n\nEl espacio donde trabajo está pensado para que te sientas tranquilo desde que llegas. Sin música alta, sin luces artificiales, sin prisas. Solo tú, tu cuerpo y el tiempo que necesitas.',
    E'My name is Elias and I''m a professional massage therapist in Valencia. I''ve been doing this for over 8 years, and every day confirms I chose well.\n\nI trained in physiotherapy and specialised in therapeutic, sports and relaxation massage. I''ve worked with athletes, people with chronic pain, and those who simply need to stop.\n\nMy approach is simple: listen to the body, understand what it needs, and work with precision. No generic protocols. Every session is different because every person is.\n\nThe space where I work is designed so you feel calm from the moment you arrive. No loud music, no harsh lights, no rush. Just you, your body, and the time you need.',
    E'Меня зовут Элиас, я профессиональный массажист в Валенсии. Я занимаюсь этим более 8 лет, и каждый день подтверждает, что я сделал правильный выбор.\n\nЯ учился физиотерапии и специализировался на лечебном, спортивном и расслабляющем массаже. Работал со спортсменами, людьми с хронической болью и теми, кому просто нужно остановиться.\n\nМой подход прост: слушать тело, понимать, что ему нужно, и работать точно. Никаких шаблонов. Каждый сеанс уникален, потому что уникален каждый человек.\n\nПространство, в котором я работаю, создано так, чтобы вы расслаблялись с порога. Без громкой музыки, без яркого света, без спешки. Только вы, ваше тело и нужное вам время.'),
  ('about_space_label', 'about_page', 'About — space section label (small caps)', 13,
    'El espacio', 'The space', 'Пространство'),
  ('about_space_title', 'about_page', 'About — space section title', 14,
    'El espacio', 'The space', 'Пространство'),
  ('about_space_paragraphs', 'about_page', 'About — space description (separate paragraphs with a blank line)', 15,
    E'Mi consulta está en el centro de Valencia, en una zona tranquila y accesible. Es un espacio luminoso, cálido y diseñado para que puedas desconectar desde el primer momento.\n\nTrabajo con productos naturales y materiales de calidad. Todo está cuidado para que la experiencia sea completa y agradable.',
    E'My practice is in central Valencia, in a quiet and accessible area. It''s a bright, warm space designed to help you switch off from the very first moment.\n\nI work with natural products and quality materials. Every detail is cared for so the experience is complete and enjoyable.',
    E'Мой кабинет находится в центре Валенсии, в тихом и доступном районе. Это светлое и тёплое пространство, созданное для того, чтобы вы могли расслабиться с первой минуты.\n\nЯ использую натуральные продукты и качественные материалы. Все продумано, чтобы опыт был полным и приятным.'),
  ('about_gallery_title', 'about_page', 'About — gallery section title', 16,
    'Galería', 'Gallery', 'Галерея'),
  ('about_seo_title', 'about_page', 'About — SEO meta title', 17,
    'Sobre Mí — Elias Masaje Valencia', 'About Me — Elias Masaje Valencia', 'Обо мне — Elias Masaje Валенсия'),
  ('about_seo_description', 'about_page', 'About — SEO meta description', 18,
    'Conoce a Elias, masajista profesional en Valencia con experiencia en masaje descontracturante, relajante y deportivo.',
    'Meet Elias, a professional massage therapist in Valencia specializing in deep tissue, relaxation and sports massage.',
    'Познакомьтесь с Элиасом — профессиональным массажистом в Валенсии с опытом в лечебном, расслабляющем и спортивном массаже.')
ON CONFLICT (content_key) DO NOTHING;